### ISSUE TITLE
incorrect result in running nucenes bag

### ISSUE THREAD

**Issue by Miki-lin** [zzningxp/PointPillars-ROS#4]
I run rosbag with zz0809_512_e50 model, but not get incorrect box marks in rviz.
![Screenshot from 2022-11-25 15-12-56](https://user-images.githubusercontent.com/54935281/203922946-32131360-0568-4f9a-b060-38f603e1378c.png)

**Comment by zzningxp** [comment]
How about the other models?

**Comment by qiumeng6** [comment]
你好，我这里也测试了多个模型，可视化后的结果与上图差不多，不知道哪里出的问题呀（用的是X86会有影响吗？）。

**Comment by Miki-lin** [comment]
> How about the other models?
Other models don't have rosbag, so there's no test, I can test bin later.
Can you test the rosbag you give to find out the problem?

**Comment by Miki-lin** [comment]
> 你好，我这里也测试了多个模型，可视化后的结果与上图差不多，不知道哪里出的问题呀（用的是X86会有影响吗？）。

我也是，3D框对不上，可能我还在看里面的代码

**Comment by zzningxp** [comment]
I reproduce the same bug myself.
z0809_e50, z0808_e50 and cbgs_pp_multihead all have the same problem. 
It should be produced by new code of boolmap vfe. If you want to quick fix, you can checkout to an older version before boolmap, like 3c9940 or earlier.

I will fix this bug soon.

And, z1117_boolmap_e40 is good.

**Comment by zzningxp** [comment]
@Miki-lin Now the bug is fixed at git@bc3ef4b 
Thank you for reporting.

**Comment by zzningxp** [comment]
The bug is triggered by CUDA input data array.
With the same code, it would not be triggered in boolmap vfe. 
I think that the old initialization of input array will cause conflicts with some parts of the CUDA concurrent operation of pillars VFE.

**Comment by Miki-lin** [comment]
I fix it, thank you very much!
