### ISSUE TITLE
关于在自己数据集上训练的问题

### ISSUE THREAD

**Issue by Xiaotianzhi** [zzningxp/PointPillars-ROS#8]
您好，很感谢您精彩的工作，对我帮助很大。我想用自己的数据集训练一下，所以仍旧有些训练模型的疑问，您的模型是在OpenPCDet下训练的，如果不考虑速度问题，是否可以将OpenPCDet框架下.pth的pointpillars模型转化为onnx模型放到该代码中运行呢？  此外还有您的这一标题下“How to train boolmap model?” 是否可以提供一些关键细节呢？谢谢。

**Comment by zzningxp** [comment]
I use https://github.com/hova88/OpenPCDet to train my model.
However, you should implement boolmap code to the training project by python, which is very easy.
I am sorry I did not release the code.

**Comment by Xiaotianzhi** [comment]
谢谢您的回复，我理解的意思就是将您推荐的工程（https://github.com/Livox-SDK/livox_detection）中的boolmap.py文件加入到OpenPCDet框架下的我需要的训练文件中，在训练过程中使用到这种快速体素特征提取器，我的理解对么？刚接触这方面不久，所以疑问有些多，期待您的回复，再次感谢。

**Comment by Xiaotianzhi** [comment]
谢谢您的回复，我理解的意思就是将您推荐的工程（ “https://github.com/Livox-SDK/livox_detection”  ）中的boolmap.py文件加入到OpenPCDet框架下的我需要的训练文件中，在训练过程中使用到这种快速体素特征提取器，我的理解对么？刚接触这方面不久，所以疑问有些多，期待您的回复，再次感谢。

**Comment by zzningxp** [comment]
Not the whole python file, but you can try the core functions.
